name: ComboUtils
main: us.jin.my_utils.Main
version: 1.0
author: Jin
commands:
  sethome:
    description: This sets the spawn of a player.
    usage: /<command>
    permission: ComboUtils.BasicPermission
    permission-message: You do not have enough power you fuck

permissions:
  ComboUtils.BasicPermission:
    default: true


