name: SetHome
main: us.jin.my_utils.Main
version: 1.0
author: Jin
commands:
  sethome:
    aliases: [sh]
    description: This sets the spawn of a player.
    usage: /<command> [player]
    permission: <plugin name>.setHome
    permission-message: You do not have enough power you fuck


