name: CreeperSpawn
version: 1.0
author: MEEEEE
main: us.jin.plugin_tools.Main
description: Spawns 10 creepeeeeeers

commands:
  creepspawn:
    aliases: [cs]
    description: /cs to spawns 10 creepeeeeeers
